language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install nose coverage click codeclimate-test-reporter

script:
  - nosetests --with-doctest --with-coverage --cover-package=migrator

after_success:
  - codeclimate-test-reporter
