language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install nose coverage click

script: nosetests --with-doctest --with-coverage --cover-erase --cover-package=migrator

addons:
    code_climate:
        repo_token: e274d9f1e9bdd89191bdecc9f05356983eb05967021808ce89c53b7817c37b39
